export default {
  login: "ahmeraltaf7",
  id: 55451381,
  node_id: "MDQ6VXNlcjU1NDUxMzgx",
  avatar_url: "https://avatars1.githubusercontent.com/u/55451381?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ahmeraltaf7",
  html_url: "https://github.com/ahmeraltaf7",
  followers_url: "https://api.github.com/users/ahmeraltaf7/followers",
  following_url:
    "https://api.github.com/users/ahmeraltaf7/following{/other_user}",
  gists_url: "https://api.github.com/users/ahmeraltaf7/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ahmeraltaf7/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ahmeraltaf7/subscriptions",
  organizations_url: "https://api.github.com/users/ahmeraltaf7/orgs",
  repos_url: "https://api.github.com/users/ahmeraltaf7/repos",
  events_url: "https://api.github.com/users/ahmeraltaf7/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ahmeraltaf7/received_events",
  type: "User",
  site_admin: false,
  name: "Ahmer Altaf",
  company: null,
  blog: "",
  location: "Pakistan,Karachi",
  email: null,
  hireable: null,
  bio: "I'm a web developer with a passion for Front-End development.",
  twitter_username: null,
  public_repos: 0,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-09-17T15:01:20Z",
  updated_at: "2020-11-06T06:18:53Z",
};
